  version: '3.8'

  services:
    mysql:
      image: mysql:8.0
      container_name: mysql-strapi
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: strapi
        MYSQL_USER: strapi
        MYSQL_PASSWORD: password
      ports:
        - '3306:3306'
      volumes:
        - mysql_data:/var/lib/mysql
      healthcheck:
        test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=password"]
        interval: 10s
        timeout: 5s
        retries: 3

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      platform: linux/amd64
      environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: password
      ports:
        - '8080:80'
      depends_on:
        - mysql

  volumes:
    mysql_data:
