on:
    push:
        branches:
            - main

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 20.0.0
      uses: actions/setup-node@v2
      with:
        node-version: '20.0.0'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

    - name: 📂 List Local Files
      run: |
        ls -R ./build
        
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local_dir: ./build
        remote_dir: /build
# //162.241.2.243
    - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$key" > ~/.ssh/staging.key
          chmod 400 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $host
            User $username
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}


ssh staging 'cd /home/app/web-api/;git fetch'